<?php

/**
 * Implements hook_mail().
 */
function email_messages_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html';

  switch ($key) {
    case 'notification':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_views_data_alter().
 */
function email_messages_views_data_alter(&$data) {
  $data['email_message_log']['uid']['filter']['id'] = 'user_name';
  $data['email_message_log']['message']['filter']['id'] = 'email_message';
}
